baseURL = "https://paramsingh.dev/"
languageCode = "en-us"
title = "Blog and projects"
theme = ""

pygmentsCodefences = true
pygmentsStyle = "friendly"

 [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/USERNAME"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/USERNAME"

